import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const options = Object.fromEntries(process.argv.slice(2).map((item) => { const [key, value] = item.replace(/^--/, '').split('='); return [key, value ?? true]; }));
const browserName = options.browser || 'chrome';
const baseUrl = String(options.url || 'http://127.0.0.1:8765').replace(/\/$/, '');
const candidates = process.platform === 'win32' ? {
  chrome: ['C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'],
  edge: ['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', 'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe']
} : {
  chrome: ['/usr/bin/google-chrome', '/usr/bin/chromium', '/usr/bin/chromium-browser'],
  edge: ['/usr/bin/microsoft-edge']
};
const executable = candidates[browserName]?.find(fs.existsSync);
if (!executable) { console.error(`找不到浏览器：${browserName}`); process.exit(2); }

const profile = fs.mkdtempSync(path.join(os.tmpdir(), `oet-${browserName}-`));
const child = spawn(executable, [
  '--headless=new', '--disable-gpu', '--no-first-run', '--disable-default-apps', '--disable-extensions',
  '--disable-background-networking', '--disable-component-update', '--disable-sync', '--metrics-recording-only',
  '--mute-audio', '--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--remote-debugging-port=0', `--user-data-dir=${profile}`, 'about:blank'
], { stdio: ['ignore', 'ignore', 'pipe'] });

function devtoolsUrl() {
  return new Promise((resolve, reject) => {
    let buffer = ''; const timer = setTimeout(() => reject(new Error('浏览器调试端口启动超时')), 10000);
    child.stderr.on('data', (chunk) => { buffer += chunk; const match = buffer.match(/DevTools listening on (ws:\/\/[^\s]+)/); if (match) { clearTimeout(timer); resolve(match[1]); } });
    child.once('exit', (code) => { clearTimeout(timer); reject(new Error(`浏览器提前退出：${code}`)); });
  });
}

class CDP {
  constructor(url) { this.socket = new WebSocket(url); this.id = 0; this.pending = new Map(); this.events = new Map(); this.socket.onmessage = (event) => { const message = JSON.parse(event.data); if (message.id) { const handler = this.pending.get(message.id); this.pending.delete(message.id); if (message.error) handler?.reject(new Error(message.error.message)); else handler?.resolve(message.result); } else for (const handler of this.events.get(message.method) || []) handler(message.params); }; }
  async open() { if (this.socket.readyState === WebSocket.OPEN) return; await new Promise((resolve, reject) => { this.socket.onopen = resolve; this.socket.onerror = reject; }); }
  send(method, params = {}) { return new Promise((resolve, reject) => { const id = ++this.id; this.pending.set(id, { resolve, reject }); this.socket.send(JSON.stringify({ id, method, params })); }); }
  on(method, handler) { const handlers = this.events.get(method) || []; handlers.push(handler); this.events.set(method, handlers); }
  close() { this.socket.close(); }
}

function delay(milliseconds) { return new Promise((resolve) => setTimeout(resolve, milliseconds)); }
async function main() {
  const browserWs = await devtoolsUrl(); const endpoint = new URL(browserWs); const httpBase = `http://${endpoint.host}`;
  const target = (await (await fetch(`${httpBase}/json/list`)).json()).find((item) => item.type === 'page');
  if (!target) throw new Error('未找到页面目标');
  const cdp = new CDP(target.webSocketDebuggerUrl); await cdp.open();
  const errors = []; const requests = [];
  cdp.on('Runtime.exceptionThrown', (event) => errors.push(event.exceptionDetails?.text || '运行时异常'));
  cdp.on('Log.entryAdded', (event) => { if (event.entry?.level === 'error') errors.push(event.entry.text); });
  cdp.on('Runtime.consoleAPICalled', (event) => { if (event.type === 'error') errors.push(event.args?.map((arg) => arg.value || arg.description).join(' ')); });
  cdp.on('Network.requestWillBeSent', (event) => requests.push(event.request.url));
  await Promise.all(['Page.enable','Runtime.enable','Log.enable','Network.enable'].map((method) => cdp.send(method)));
  await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 800, deviceScaleFactor: 1, mobile: false });
  async function evaluate(expression) { const response = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (response.exceptionDetails) throw new Error(response.exceptionDetails.text); return response.result.value; }
  async function navigate(route) {
    await cdp.send('Page.navigate', { url: `${baseUrl}${route}` });
    for (let attempt = 0; attempt < 50; attempt += 1) {
      await delay(100);
      const ready = await evaluate(`document.readyState === 'complete' && ${route === '/' ? "document.querySelector('#result-count')?.textContent !== '正在加载工具…'" : 'true'}`);
      if (ready) return;
    }
    throw new Error(`页面加载超时：${route}`);
  }
  if (options['offline-picker']) {
    await cdp.send('Page.navigate', { url: `${baseUrl}/index.html` });
    for (let attempt = 0; attempt < 50; attempt += 1) { await delay(100); if (await evaluate(`document.readyState === 'complete'`)) break; }
    await delay(250);
    const check = await evaluate(`(() => { const input=document.querySelector('#names'); if (!input) return {location:location.href}; input.value='示例甲\\n示例乙'; input.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('#roll-duration').value='0'; document.querySelector('#draw').click(); return {location:location.href,status:document.querySelector('#status').textContent,downloadVisible:document.body.textContent.includes('下载离线包'),overflow:document.documentElement.scrollWidth>innerWidth}; })()`);
    const unexpectedRequests = requests.filter((url) => /^https?:/i.test(url)); const passed = /\/tools\/random-picker\/index\.html$/.test(check.location) && /已抽中/.test(check.status) && !check.downloadVisible && !check.overflow && errors.length === 0 && unexpectedRequests.length === 0;
    console.log(JSON.stringify({ browser: browserName, mode: 'offline-file', passed, check, errors, unexpectedRequests }, null, 2)); cdp.close(); if (!passed) process.exitCode = 1; return;
  }
  const checks = {};
  await navigate('/'); checks.home = await evaluate(`({ cards: document.querySelectorAll('.tool-card').length, downloads: document.querySelectorAll('.tool-card__download').length, shares: document.querySelectorAll('.tool-card__share').length, subjects: document.querySelectorAll('#subject-list button').length, github: document.querySelector('[data-github-link]')?.href, count: document.querySelector('#result-count')?.textContent, newTab: document.querySelector('#tool-grid .tool-card__title a')?.target === '_blank', overflow: document.documentElement.scrollWidth > innerWidth })`);
  checks.share = await evaluate(`(() => { const button=document.querySelector('.share-button'); if(!button) return {hasButton:false}; button.click(); const dialog=document.querySelector('.share-dialog'); const result={hasButton:true,dialog:!!dialog,qr:!!document.querySelector('.share-qr__canvas'),links:document.querySelectorAll('.share-link').length,url:document.querySelector('.share-dialog__url input')?.value}; document.querySelector('.share-dialog .icon-btn')?.click(); result.closed=!document.querySelector('.share-dialog'); document.querySelector('.tool-card__share').click(); result.cardUrl=document.querySelector('.share-dialog__url input')?.value; document.querySelector('.share-dialog .icon-btn')?.click(); return result; })()`);
  checks.fuzzySearch = await evaluate(`(() => { const search=document.querySelector('#tool-search'); search.value='接晓'; search.dispatchEvent(new Event('input',{bubbles:true})); const result={cards:document.querySelectorAll('#tool-grid .tool-card').length,name:document.querySelector('#tool-grid .tool-card__title')?.textContent}; document.querySelector('#clear-search').click(); return result; })()`);
  checks.subjectFilter = await evaluate(`(() => { const button=document.querySelector('[data-subject="mathematics"]'); button.click(); const result={cards:document.querySelectorAll('#tool-grid .tool-card').length,name:document.querySelector('#tool-grid .tool-card__title')?.textContent}; document.querySelector('#clear-search').click(); return result; })()`);
  if (options.screenshot) {
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 1200, height: 900, deviceScaleFactor: 1, mobile: false });
    const capture = await cdp.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); const targetPath = path.resolve(String(options.screenshot)); fs.mkdirSync(path.dirname(targetPath), { recursive: true }); fs.writeFileSync(targetPath, Buffer.from(capture.data, 'base64'));
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 800, deviceScaleFactor: 1, mobile: false });
  }
  await navigate('/tools/random-picker/index.html'); checks.picker = await evaluate(`(() => { const input=document.querySelector('#names'); input.value='示例甲\\n示例乙\\n示例甲'; input.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('#remove-picked').checked=true; document.querySelector('#roll-duration').value='0'; document.querySelector('#draw').click(); return {status:document.querySelector('#status').textContent,overflow:document.documentElement.scrollWidth>innerWidth}; })()`);
  await navigate('/tools/random-group/index.html'); checks.group = await evaluate(`(() => { const input=document.querySelector('#names'); input.value='示例甲\\n示例乙\\n示例丙\\n示例丁\\n示例戊'; input.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('#btnBySize').click(); document.querySelector('#amount').value='2'; document.querySelector('#group').click(); return {groups:document.querySelectorAll('.group-card').length,status:document.querySelector('#status').textContent,overflow:document.documentElement.scrollWidth>innerWidth}; })()`);
  await navigate('/tools/classroom-timer/index.html'); checks.timerStarted = await evaluate(`(() => { document.querySelector('#minutes').value='0'; document.querySelector('#seconds').value='1'; document.querySelector('#start').click(); return document.querySelector('#status').textContent; })()`); await delay(1300); checks.timer = await evaluate(`({display:document.querySelector('#display').textContent,finished:!document.querySelector('#finished').hidden,overflow:document.documentElement.scrollWidth>innerWidth})`);
  await navigate('/tools/text-cleaner/index.html'); checks.cleaner = await evaluate(`(() => { const input=document.querySelector('#source'); input.value='  示例甲  \\n\\n\\n示例甲  '; input.dispatchEvent(new Event('input',{bubbles:true})); for (const name of ['trimLines','collapseBlankLines','dedupeLines']) { const box=document.querySelector('[data-option="'+name+'"]'); box.checked=true; box.dispatchEvent(new Event('change',{bubbles:true})); } return {output:document.querySelector('#output').value,summary:document.querySelector('#summary').textContent,overflow:document.documentElement.scrollWidth>innerWidth}; })()`);
  await navigate('/tools/score-statistics/index.html'); checks.score = await evaluate(`(() => { document.querySelector('#scores').value='分数\\n0\\n60\\n80\\n90\\n100'; document.querySelector('#calculate').click(); return {status:document.querySelector('#status').textContent,result:document.querySelector('#result').textContent,overflow:document.documentElement.scrollWidth>innerWidth}; })()`);
  await navigate('/tools/handwriting-digits/index.html'); checks.handwritingGated = await evaluate(`({disabled:document.querySelector('#startBtn').disabled,hint:document.querySelector('#startHint').textContent})`); await evaluate(`(() => { HTMLAnchorElement.prototype.click=function(){}; window.showDirectoryPicker=async()=>{const w={write:async()=>{},close:async()=>{}}; const h={name:'test',getDirectoryHandle:async()=>h,getFileHandle:async()=>({createWritable:async()=>w})}; return h;}; const id=document.querySelector('#studentId'); id.value='T001'; id.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('#selectFolderBtn').click(); return true; })()`); await delay(150); await evaluate(`(() => { document.querySelector('#startBtn').click(); document.querySelector('#saveBtn').click(); return true; })()`); await delay(700); checks.handwriting = await evaluate(`({count:document.querySelector('#collectedCount').textContent,max:document.querySelector('#maxCountLabel').textContent,status:document.querySelector('#status').textContent,exportVisible:!document.querySelector('#exportAllBtn').hidden,fullscreen:!!document.querySelector('#fullscreenBtn'),target:document.querySelector('#targetNumber').textContent,overflow:document.documentElement.scrollWidth>innerWidth})`);
  await navigate('/tools/noise-meter/index.html'); checks.noise = await evaluate(`(() => { const hasStart=!!document.querySelector('#startBtn'); document.querySelector('#startBtn').click(); return {hasStart,threshold:document.querySelector('#threshold').value,overflow:document.documentElement.scrollWidth>innerWidth}; })()`); await delay(700); checks.noiseStatus = await evaluate(`({status:document.querySelector('#status').textContent,stopEnabled:!document.querySelector('#stopBtn').disabled})`);
  await navigate('/tools/fullscreen-clock/index.html'); checks.clock = await evaluate(`({time:document.querySelector('#clockTime').textContent,date:document.querySelector('#clockDate').textContent,hasFullscreen:!!document.querySelector('#fullscreenBtn'),overflow:document.documentElement.scrollWidth>innerWidth})`);
  await navigate('/tools/pomodoro-timer/index.html'); checks.pomodoro = await evaluate(`(() => { const before=document.querySelector('#timerDisplay').textContent; document.querySelector('#startBtn').click(); document.querySelector('#resetBtn').click(); return {before,phase:document.querySelector('#phaseLabel').textContent,overflow:document.documentElement.scrollWidth>innerWidth}; })()`);
  await navigate('/tools/markdown-to-word/index.html'); checks.markdown = await evaluate(`(() => { HTMLAnchorElement.prototype.click=function(){}; const preview=document.querySelector('#preview'); const result={hasHeading:!!preview.querySelector('h1'),hasTable:!!preview.querySelector('table'),hasMath:!!preview.querySelector('math')}; document.querySelector('#convertBtn').click(); result.status=document.querySelector('#status').textContent; result.overflow=document.documentElement.scrollWidth>innerWidth; return result; })()`);
  await navigate('/tools/image-editor/index.html'); await evaluate(`(async () => { const canvas=document.createElement('canvas'); canvas.width=600; canvas.height=450; const ctx=canvas.getContext('2d'); const grad=ctx.createLinearGradient(0,0,600,450); grad.addColorStop(0,'#1e3a8a'); grad.addColorStop(1,'#f59e0b'); ctx.fillStyle=grad; ctx.fillRect(0,0,600,450); for(let i=0;i<6000;i+=1){ ctx.fillStyle='rgba('+(i%255)+','+((i*7)%255)+','+((i*13)%255)+',0.6)'; ctx.fillRect(Math.random()*600,Math.random()*450,3,3); } const blob=await new Promise((resolve)=>canvas.toBlob(resolve,'image/jpeg',0.9)); const file=new File([blob],'photo.jpg',{type:'image/jpeg'}); const transfer=new DataTransfer(); transfer.items.add(file); const input=document.querySelector('#fileInput'); input.files=transfer.files; input.dispatchEvent(new Event('change',{bubbles:true})); return true; })()`); await delay(900); checks.image = await evaluate(`({canvasVisible:!document.querySelector('#canvasWrap').hidden,meta:document.querySelector('#imageMeta').textContent,output:document.querySelector('#outputInfo').textContent,format:document.querySelector('#formatSelect').value,hasDownload:!document.querySelector('#downloadBtn').disabled,overflow:document.documentElement.scrollWidth>innerWidth})`); checks.imageQuality = await evaluate(`(async () => { const setQuality=async (q)=>{ const el=document.querySelector('#quality'); el.value=String(q); el.dispatchEvent(new Event('input',{bubbles:true})); await new Promise((r)=>setTimeout(r,700)); return document.querySelector('#outputInfo').textContent; }; const high=await setQuality(95); const low=await setQuality(40); return {high,low}; })()`); checks.imageCompress = await evaluate(`(async () => { document.querySelector('#targetSize').value='25'; document.querySelector('#compressBtn').click(); await new Promise((r)=>setTimeout(r,1800)); return {status:document.querySelector('#status').textContent,output:document.querySelector('#outputInfo').textContent}; })()`); checks.imagePngCompress = await evaluate(`(async () => { const format=document.querySelector('#formatSelect'); format.value='image/png'; format.dispatchEvent(new Event('change',{bubbles:true})); document.querySelector('#targetSize').value='30'; document.querySelector('#compressBtn').click(); await new Promise((r)=>setTimeout(r,2400)); return {status:document.querySelector('#status').textContent,output:document.querySelector('#outputInfo').textContent}; })()`);
  await navigate('/tools/pdf-toolkit/index.html'); checks.pdf = await evaluate(`(async () => { const { PDFDocument } = window.PDFLib; const doc = await PDFDocument.create(); doc.addPage(); doc.addPage(); doc.addPage(); const bytes = await doc.save(); const file = new File([bytes], 'test.pdf', { type: 'application/pdf' }); const transfer = new DataTransfer(); transfer.items.add(file); const input = document.querySelector('#fileInput'); input.files = transfer.files; input.dispatchEvent(new Event('change',{bubbles:true})); await new Promise((r)=>setTimeout(r,1600)); return { railCount: document.querySelectorAll('#rail .pdf-thumb-card').length, pageInfo: document.querySelector('#pageInfo').textContent, stageWidth: document.querySelector('#stageCanvas').width, overflow: document.documentElement.scrollWidth>innerWidth }; })()`); checks.pdfExtract = await evaluate(`(async () => { document.querySelector('.pdf-mode[data-mode="extract"]').click(); await new Promise((r)=>setTimeout(r,500)); document.querySelector('#rail .pdf-thumb-card[data-page="1"]').click(); document.querySelector('#rail .pdf-thumb-card[data-page="2"]').click(); await new Promise((r)=>setTimeout(r,200)); const count = document.querySelector('#extractCount').textContent; HTMLAnchorElement.prototype.click = function(){}; document.querySelector('#extractBtn').click(); await new Promise((r)=>setTimeout(r,800)); return { count, status: document.querySelector('#status').textContent }; })()`); checks.pdfEdit = await evaluate(`(async () => { document.querySelector('.pdf-mode[data-mode="edit"]').click(); await new Promise((r)=>setTimeout(r,1400)); const canvas = document.querySelector('#stageCanvas'); document.querySelector('#textToolBtn').click(); const rect = canvas.getBoundingClientRect(); canvas.dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:rect.left+rect.width*0.4,clientY:rect.top+rect.height*0.4})); await new Promise((r)=>setTimeout(r,300)); const overlay = document.querySelector('.pdf-overlay--text'); if (overlay) { overlay.textContent = 'Hello'; overlay.dispatchEvent(new Event('blur')); } await new Promise((r)=>setTimeout(r,300)); return { width: canvas.width, overlays: document.querySelectorAll('.pdf-overlay').length, text: overlay ? overlay.textContent : '', status: document.querySelector('#status').textContent, overflow: document.documentElement.scrollWidth>innerWidth }; })()`);
  await cdp.send('Emulation.setPageScaleFactor', { pageScaleFactor: 2 }); checks.scale200 = await evaluate(`({scale:visualViewport.scale,actionVisible:!!document.querySelector('#calculate')?.getClientRects().length,overflow:document.documentElement.scrollWidth>innerWidth})`);
  const unexpectedRequests = requests.filter((url) => /^https?:/i.test(url) && !url.startsWith(baseUrl) && !/\.workers\.dev\//i.test(url));
  const passed = checks.home.cards === 12 && checks.home.downloads === 12 && checks.home.shares === 12 && checks.home.subjects >= 2 && /github\.com\/xingyezn\/OpenEduTools/.test(checks.home.github) && checks.home.count === '找到 12 个工具' && checks.home.newTab && checks.share.hasButton && checks.share.dialog && checks.share.qr && checks.share.links >= 4 && checks.share.closed && /\/tools\//.test(checks.share.cardUrl || '') && checks.fuzzySearch.cards === 1 && checks.fuzzySearch.name === '随机点名' && checks.subjectFilter.cards === 1 && checks.subjectFilter.name === '成绩统计' && /已抽中/.test(checks.picker.status) && checks.group.groups === 3 && checks.timer.finished && checks.cleaner.output === '示例甲\n' && /已完成 5 个分数/.test(checks.score.status) && checks.handwritingGated.disabled === false && /学号/.test(checks.handwritingGated.hint) && checks.handwriting.count === '1' && checks.handwriting.max === '100' && /已保存/.test(checks.handwriting.status) && checks.handwriting.exportVisible && checks.handwriting.fullscreen && /^[0-9]$/.test(checks.handwriting.target) && checks.noise.hasStart && checks.noise.threshold === '60' && /测量中/.test(checks.noiseStatus.status) && checks.noiseStatus.stopEnabled && /^\d{2}:\d{2}:\d{2}$/.test(checks.clock.time) && checks.clock.date.length > 0 && checks.clock.hasFullscreen && checks.pomodoro.before === '25:00' && checks.pomodoro.phase === '专注' && checks.markdown.hasHeading && checks.markdown.hasTable && checks.markdown.hasMath && /已生成 Word/.test(checks.markdown.status) && checks.image.canvasVisible && /600/.test(checks.image.meta) && checks.image.hasDownload && checks.image.format === 'image/jpeg' && /预估约/.test(checks.image.output) && checks.imageQuality.high !== checks.imageQuality.low && /已压缩/.test(checks.imageCompress.status) && /已压缩/.test(checks.imagePngCompress.status) && checks.pdf.railCount === 3 && checks.pdf.stageWidth > 0 && /1 \/ 3/.test(checks.pdf.pageInfo) && /已选 2/.test(checks.pdfExtract.count) && /已提取 2 页/.test(checks.pdfExtract.status) && checks.pdfEdit.width > 0 && checks.pdfEdit.overlays >= 1 && /Hello/.test(checks.pdfEdit.text) && !Object.values(checks).some((check) => check?.overflow) && errors.length === 0 && unexpectedRequests.length === 0;
  console.log(JSON.stringify({ browser: browserName, passed, checks, errors, unexpectedRequests }, null, 2)); cdp.close(); if (!passed) process.exitCode = 1;
}

try { await main(); } catch (error) { console.error(error.stack || error.message); process.exitCode = 1; } finally { child.kill(); try { fs.rmSync(profile, { recursive: true, force: true }); } catch { /* temporary profile cleanup is best effort */ } }
